import Header from "@/components/Header/Header";
import "./globals.css";
import { useQuery, QueryClientProvider } from "react-query";
import Footer from "@/components/Footer/Footer";
import MainProvider from "@/provider/MainProvider";

export const metadata = {
  title: "NEXTFlix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MainProvider>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </MainProvider>
    </html>
  );
}
